;;; local-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ../site/bison-mode.el

(add-to-list 'auto-mode-alist '("\\.y\\'" . bison-mode))
(add-to-list 'auto-mode-alist '("\\.l\\'" . flex-mode))
(add-to-list 'auto-mode-alist '("\\.jison\\'" . jison-mode))
(autoload 'bison-mode "../site/bison-mode" "\
Major mode for editing bison/yacc files.

(fn)" t)
(autoload 'jison-mode "../site/bison-mode" "\
Major mode for editing jison files.

(fn)" t)
(autoload 'flex-mode "../site/bison-mode" "\
Major mode for editing flex files. (bison-mode by any other name)

(fn)" t)
(register-definition-prefixes "../site/bison-mode" '("bison-"))


;;; Generated autoloads from ../site/cmake-mode.el

(autoload 'cmake-mode "../site/cmake-mode" "\
Major mode for editing CMake source files.

(fn)" t)
(autoload 'cmake-command-run "../site/cmake-mode" "\
Runs the command cmake with the arguments specified.  The
optional argument topic will be appended to the argument list.

(fn TYPE &optional TOPIC BUFFER)" t)
(autoload 'cmake-command-run-help "../site/cmake-mode" "\
`cmake-command-run' but rendered in `rst-mode'.

(fn TYPE &optional TOPIC BUFFER)" t)
(autoload 'cmake-help-list-commands "../site/cmake-mode" "\
Prints out a list of the cmake commands." t)
(autoload 'cmake-help-command "../site/cmake-mode" "\
Prints out the help message for the command the cursor is on." t)
(autoload 'cmake-help-module "../site/cmake-mode" "\
Prints out the help message for the module the cursor is on." t)
(autoload 'cmake-help-variable "../site/cmake-mode" "\
Prints out the help message for the variable the cursor is on." t)
(autoload 'cmake-help-property "../site/cmake-mode" "\
Prints out the help message for the property the cursor is on." t)
(autoload 'cmake-help "../site/cmake-mode" "\
Queries for any of the four available help topics and prints out the appropriate page." t)
(add-to-list 'auto-mode-alist '("CMakeLists\\.txt\\'" . cmake-mode))
(add-to-list 'auto-mode-alist '("\\.cmake\\'" . cmake-mode))
(register-definition-prefixes "../site/cmake-mode" '("cmake-"))


;;; Generated autoloads from ../site/fasm-mode.el

(autoload 'fasm-mode "../site/fasm-mode" "\
Major mode for editing assembly in FASM format.

(fn)" t)
(register-definition-prefixes "../site/fasm-mode" '("fasm-"))


;;; Generated autoloads from ../site/gas-mode.el

(autoload 'gas-mode "../site/gas-mode" "\
Major mode for editing assembler code.

Commands:

(Some of these commands may exhibit slightly different behaviour if point
is on a C syntax line.)

\\[indent-for-tab-command]  indent the field(s) point is on.  If it already is in its position, 
  move on to the next field on the line.

\\[gas-indent-backward]  Move to the previous field.

\\[gas-comment]  When no region is active, starts a comment sequence:
  - If a comment is present and point is not at its start, jump there.
  - Else start a comment.  If there already is one, increase its comment level.
    What that is and what it does, is best explained when you try
    it out: Move to en empty line, then type \\[gas-comment] and
    then repeatedly \\[gas-comment] or \\[gas-comment-char].
  Calls \\[gas-comment-dwim] (see below) if the region is active.

\\[forward-sexp]  If you're on a highlighted symbol, jump to its next 
  occurence.  Else do `forward-sexp' like in text mode.

\\[backward-sexp]  If you're on a highlighted symbol, jump to its previous
  occurence.  Else do `backward-sexp' like in text mode.

\\[gas-comment-dwim] If the region starts at the leading white space
  before a comment, all full-line comments in region will be
  removed.  If the region starts on a comment, comments will be
  removed, but comments with leading white space will be left
  untouched.  Else insert triple variable `gas-comment-char's before all
  lines in region.

\\[fill-paragraph] beautifies the paragraph around
  point, i.e. it adjusts all assembly syntax fields to their
  standard positions.

\\[indent-region]  beautifies the region, i.e., adjusts all fields in region.


The following characters have a special meaning in special cases:

\\[gas-colon]  if it terminates a label:  outdent the label and
  move to opcode column.  Else, just insert \\[gas-colon] as usual.

\\[gas-comment-char]  The value which introduces an asm style comment.
  If typed in in a row after \\[gas-comment], behaves as an alias to \\[gas-comment].  else
  just insert \\[gas-comment-char].
  Can be customized to always act as alias (`gas-comment-char-starts-comment').

  Alternatively, you may use a File Variable to make it buffer local
  (which allows you to use different syntaxes in the same session).
  Note:  Setting it to a value other than ?; has not yet been tested.

\\[gas-hash]  If it starts a preprocessor directive:  Outdent it to first
  column.

Customization:  Entry on this mode runs `gas-mode-hook'.
The customization group is called 'gas'.

Special commands:
\\{gas-mode-map}" t)
(register-definition-prefixes "../site/gas-mode" '("dmsg" "gas-"))


;;; Generated autoloads from ../site/ghcid.el

(register-definition-prefixes "../site/ghcid" '("ghcid"))


;;; Generated autoloads from ../site/hindent.el

(autoload 'hindent-mode "../site/hindent" "\
Indent code with the hindent program.

Provide the following keybindings:

\\{hindent-mode-map}

This is a minor mode.  If called interactively, toggle the `HIndent
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `hindent-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'hindent-reformat-decl "../site/hindent" "\
Re-format the current declaration.

The declaration is parsed and pretty printed.  Comments are
preserved, although placement may be funky." t)
(autoload 'hindent-reformat-buffer "../site/hindent" "\
Reformat the whole buffer." t)
(autoload 'hindent-reformat-decl-or-fill "../site/hindent" "\
Re-format current declaration, or fill paragraph.

Fill paragraph if in a comment, otherwise reformat the current
declaration.  When filling, the prefix argument JUSTIFY will
cause the text to be justified, as per `fill-paragraph'.

(fn JUSTIFY)" t)
(autoload 'hindent-reformat-region "../site/hindent" "\
Reformat the region from BEG to END, accounting for indentation.

If DROP-NEWLINE is non-nil, don't require a newline at the end of
the file.

(fn BEG END &optional DROP-NEWLINE)" t)
(define-obsolete-function-alias 'hindent/reformat-decl 'hindent-reformat-decl "hindent 5.2.2")
(register-definition-prefixes "../site/hindent" '("hindent-"))


;;; Generated autoloads from ../minor-modes/hinfo.el

(defvar-keymap hinfo-mode-map "N" #'hinfo-goto-next-section "P" #'hinfo-goto-prev-section "n" #'hinfo-goto-next-state "p" #'hinfo-goto-prev-state "S" #'hinfo-goto-section "T" #'hinfo-goto-nonterminal "t" #'hinfo-goto-terminal "r" #'hinfo-goto-rule "s" #'hinfo-goto-state "g" #'hinfo-revert)
(autoload 'hinfo-mode "../minor-modes/hinfo" "\
Major mode for Happy generated info files

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.hinfo\\'" . hinfo-mode))
(register-definition-prefixes "../minor-modes/hinfo" '("hinfo-"))


;;; Generated autoloads from ../site/kbd-mode.el

(autoload 'kbd-mode "../site/kbd-mode" "\
Major mode for editing `.kbd' files.

For details, see `https://github.com/kmonad/kmonad'.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.kbd\\'" . kbd-mode))
(autoload 'kbd-mode-demo-mode "../site/kbd-mode" "\
Toggle kmonad demo mode.

This is a minor mode, in which users can test their
configurations.

This is a minor mode.  If called interactively, toggle the
`Kbd-Mode-Demo mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `kbd-mode-demo-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'kbd-mode-start-demo "../site/kbd-mode" "\
Try the current configuration in a demo buffer.
Use `kbd-mode-stop-demo' to stop the demo.  If the configuration
file has errors, the demo will not start and an error buffer will
be shown instead." t)
(register-definition-prefixes "../site/kbd-mode" '("kbd-mode-"))


;;; Generated autoloads from ../site/leg-mode.el

(register-definition-prefixes "../site/leg-mode" '("leg-mode"))


;;; Generated autoloads from ../minor-modes/nomouse.el

(autoload 'nomouse-mode "../minor-modes/nomouse" "\
Enable/Disable Mouse bindings in the current buffer.

This is a minor mode.  If called interactively, toggle the `nomouse
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `nomouse-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-nomouse-mode 'globalized-minor-mode t)
(defvar global-nomouse-mode nil "\
Non-nil if Global Nomouse mode is enabled.
See the `global-nomouse-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-nomouse-mode'.")
(custom-autoload 'global-nomouse-mode "../minor-modes/nomouse" nil)
(autoload 'global-nomouse-mode "../minor-modes/nomouse" "\
Toggle Nomouse mode in all buffers.
With prefix ARG, enable Global Nomouse mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Nomouse mode is enabled in all buffers where `nomouse--turn-on' would
do it.

See `nomouse-mode' for more information on Nomouse mode.

(fn &optional ARG)" t)
(register-definition-prefixes "../minor-modes/nomouse" '("nomouse-"))


;;; Generated autoloads from ../minor-modes/todowords.el

(autoload 'todowords-mode "../minor-modes/todowords" "\
Enable/Disable Mouse bindings in the current buffer.

This is a minor mode.  If called interactively, toggle the `todowords
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `todowords-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-todowords-mode 'globalized-minor-mode t)
(defvar global-todowords-mode nil "\
Non-nil if Global Todowords mode is enabled.
See the `global-todowords-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-todowords-mode'.")
(custom-autoload 'global-todowords-mode "../minor-modes/todowords" nil)
(autoload 'global-todowords-mode "../minor-modes/todowords" "\
Toggle Todowords mode in all buffers.
With prefix ARG, enable Global Todowords mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Todowords mode is enabled in all buffers where `todowords--turn-on'
would do it.

See `todowords-mode' for more information on Todowords mode.

(fn &optional ARG)" t)
(register-definition-prefixes "../minor-modes/todowords" '("todowords-"))

;;; End of scraped data

(provide 'local-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; local-loaddefs.el ends here
