#!/bin/bash

dict_list=`dict -D | awk 'NR>1 {print $1}' | sort`
dictionary_word=( `yad --title="Dictionary" --buttons-layout="center" \
    --form --separator=" " --item-separator="\n" --complete="regex" \
    --field="Dictionary:CE" "$dict_list" \
    --field="word:CBE" "" \
    --button "go"` )
EXITCODE=$?

dictionary=${dictionary_word[0]}
word=${dictionary_word[1]}

echo "${dictionary_word[@]}"
echo "$dictionary"
echo "$word"

if [ ! -z "$word" -a ! -z "$dictionary" ]
then 
    meaning=`dict -f -d "$dictionary" "$word"`
    valid_def=`echo "$meaning" | grep "No definitions found"`
fi

if [ "$EXITCODE" -eq 0 ] && 
   [ ! -z "$meaning" ] && 
   [ -z "$valid_def" ] 
then
    yad --text "$meaning" --no-buttons
else
    notify-send "You either cancelled \`dict\` or the input word has no meaning."
fi
