#!/bin/bash

## LAPTOP Dimensions ##
laptop_screen_resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
LAPTOP_SCREEN_WIDTH=${laptop_screen_resolution%x*}
LAPTOP_SCREEN_HEIGHT=${laptop_screen_resolution#*x}
VERTICAL_ITEM_COUNT=25
get_mid_X() {
    local width
    width="$1"
    printf "%d" $(( LAPTOP_SCREEN_WIDTH/2 - width/2 ))
}
get_mid_Y() {
    printf "%d" $(( LAPTOP_SCREEN_HEIGHT/2 ))
}
