#!/bin/sh

DMENU_WIDTH=300
LAPTOP_SCREEN_WIDTH=${LAPTOP_SCREEN_WIDTH:-$(( $DMENU_WIDTH/2))}
LAPTOP_SCREEN_HEIGHT=${LAPTOP_SCREEN_HEIGHT:- 0}
DMENU_X=$(( $LAPTOP_SCREEN_WIDTH - $(($DMENU_WIDTH/2))))
DMENU_Y=$(( $LAPTOP_SCREEN_HEIGHT/2 ))
[ $DMENU_X -eq 0 ] && DMENU_X=810
[ $DMENU_Y -eq 0 ] && DMENU_Y=320

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
	historyfile=$cachedir/dmenu_history
else			# if no xdg dir, fall back to dotfiles in ~
	cache=$HOME/.dmenu_cache
	historyfile=$HOME/.dmenu_history
fi

IFS=:
if stest -dqr -n "$cache" $PATH; then
	stest -flx $PATH | sort -u > "$cache"
fi
unset IFS

awk -v histfile=$historyfile '
	BEGIN {
		while( (getline < histfile) > 0 ) {
			sub("^[0-9]+\t","")
			print
			x[$0]=1
		}
	} !x[$0]++ ' "$cache" \
	| dmenu -l 25 -x "$DMENU_X" -y "$DMENU_Y" -z "$DMENU_WIDTH" -p "run" "$@" \
	| awk -v histfile=$historyfile '
		BEGIN {
			FS=OFS="\t"
			while ( (getline < histfile) > 0 ) {
				count=$1
				sub("^[0-9]+\t","")
				fname=$0
				history[fname]=count
			}
			close(histfile)
		}

		{
			history[$0]++
			print
		}

		END {
			if(!NR) exit
			for (f in history)
				print history[f],f | "sort -t '\t' -k1rn >" histfile
		}
	' \
	| while read cmd; do ${SHELL:-"/bin/sh"} -c "$cmd" & done
